### ISSUE TITLE
azure_iot_security_module assumes GCC compiler

### ISSUE THREAD

**Issue by ryanwinter** [azure-rtos/netxduo#10]
This function makes no allowances for additional compilers and defaults to GCC. This produces compiler errors using other compilers such as IAR and RXCC if ASC is enabled.

https://github.com/azure-rtos/netxduo/blob/e7f92a55a41fdd7471d32f76bc512822e4ee1993/addons/azure_iot/azure_iot_security_module/iot-security-module-core/cmake-modules/asc_security_coreBuild.cmake#L16

**Comment by TiejunMS** [comment]
Fixed in 6.1.2 patch release.
