### ISSUE TITLE
About adjusting NX_PACKET->nx_packet_prepend_ptr

### ISSUE THREAD

**Issue by rk3399** [azure-rtos/netxduo#106]
In the eth driver, after applying for a data packet from the packet pool, it will nx_packet_prepend_ptr += sizeof(USHORT), and then use nx_packet_prepend_ptr as the buffer first address to receive data. I want to know why +sizeof(USHORT) is needed, because this will make nx_packet_prepend_ptr not aligned to 4 bytes, and if you want to use dma to transmit data, the dma controller will automatically align this address, making the data reception error!
![image](https://user-images.githubusercontent.com/58390397/170806851-7a42493b-0e51-4817-a6c4-585cc203e519.png)
![image](https://user-images.githubusercontent.com/58390397/170806872-eb2d52d8-4294-4486-848e-edd03eae5e78.png)

**Comment by bo-ms** [comment]
Hi @rk3399,  Thanks for asking question. The size of Ethernet header is 14 bytes, changing the prepend_ptr two bytes is to make sure TCP/IP header 4 bytes alignment.

**Comment by rk3399** [comment]
> 

Thanks for the reply. I hope to pass it to the first address of the 4-byte aligned to DMA, whether it is good suggestion?

**Comment by bo-ms** [comment]
Hi @rk3399 we encountered this requirement of 4-bytes alignment for some DMA, could you check if DMA supports offset? if support, you can directly set the first address as 4-bytes alignment, and set offset as 2, otherwise, you may need to prepare the buffer to DMA to receive data, then copy it into packet.

**Comment by xiaocq2001** [comment]
Currently USBX Host Controller Driver (HCD) calls ST's BSP HAL_HCD_ API to issue data transfer. Maybe you can try to disable DMA in HAL_HCD_ on initialization. This way FIFO is used and unaligned address should be OK.

**Comment by rk3399** [comment]
> 



> 当前 USBX 主机驱动程序 (H) 调用 ST 的 BSP HAL_API 来发出。可能您可以试用数据_HCD_初始化传输时禁用 HAL_HCD_中的 DMA。这种方式使用 FIFO 并且未命名的地址应该没有问题。

Disabling DMA does work. But this will cause CDC-ECM to occupy almost all cpu resources (each NCK will generate an interrupt), and other tasks will not be executed

**Comment by rk3399** [comment]
> Currently USBX Host Controller Driver (HCD) calls ST's BSP HAL_HCD_ API to issue data transfer. Maybe you can try to disable DMA in HAL_HCD_ on initialization. This way FIFO is used and unaligned address should be OK.

Disabling DMA does work. But this will cause CDC-ECM to occupy almost all cpu resources (each NCK will generate an interrupt), and other tasks will not be executed
