### ISSUE TITLE
STM32CubeIDE BSD fd_set类型冲突

### ISSUE THREAD

**Issue by chengshuihang** [azure-rtos/netxduo#108]
您好，我使用STM32CubeIDE环境,使能了BSD库，在编译过程中发生了类型冲突，我应该怎么解决？
![image](https://user-images.githubusercontent.com/45716763/172817684-addc1e9f-8ee3-4d5f-8bb5-988e15fdcfa5.png)
![image](https://user-images.githubusercontent.com/45716763/172817592-9c53b458-3a96-478a-944f-cdfbebd530bd.png)
![image](https://user-images.githubusercontent.com/45716763/172817840-1fd33216-06c4-4b4d-813d-3194cd5eb701.png)

**Comment by TiejunMS** [comment]
你好，请尝试在工程里定义这些宏
```
-D__suseconds_t_defined -D_STRUCT_TIMEVAL -D_SYS_SELECT_H
```

**Comment by chengshuihang** [comment]
OK,谢谢！
