### ISSUE TITLE
web http客户端接收到服务器FIN之后，无法工作

### ISSUE THREAD

**Issue by chengshuihang** [azure-rtos/netxduo#109]
您好，我在使用_nx_web_http_client_post_start_extended函数时，发生了一些问题。当服务器发送了一帧FIN后，我的_nx_web_http_client_post_start_extended函数将不再返回NX_SUCCESS，下面截图是此时HTPP句柄的信息
![d3bac74708b8cd5ee5de724a3dfe394](https://user-images.githubusercontent.com/45716763/174977070-3e1ab588-9c8e-4c89-a60e-9cd441843fba.png)
我尝试在_nx_web_http_client_connect函数中添加nx_tcp_socket_disconnect函数的调用，我不确定这个方案是否正确，但是现在http可以处理这种情况了，您们对于这种情况的处理手段有什么建议吗？
下面是我添加nx_tcp_socket_disconnect函数的位置
![image](https://user-images.githubusercontent.com/45716763/174977462-6cbf2d4d-6d84-4bb8-bc20-e897232ad54b.png)

**Comment by chengshuihang** [comment]
客户端没有设置keep-alive字段，client_ptr -> nx_web_http_client_keep_alive是false。nx_web_http_client_response_body_get这个返回值就不确定了，因为我不知道什么时候收到FIN

**Comment by wenhui-xie** [comment]
nx_web_http_client_response_body_get的用法是需要循环调用，直到收到**NX_WEB_HTTP_GET_DONE**这个status才算接收完成，如果接收完成，并且没有启用keep-alive，client会调用nx_tcp_socket_disconnect断开连接([1793行](https://github.com/azure-rtos/netxduo/blob/master/addons/web/nx_web_http_client.c#L5948:~:text=if%20((status%20!%3D%20NX_WEB_HTTP_GET_DONE)%20%7C%7C%20!(client_ptr%20%2D%3E%20nx_web_http_client_keep_alive))))。
如果中途server发了fin包导致response_body_get收包失败的话，client也会进行错误处理并主动断开连接。
所以建议你修改代码为循环调用nx_web_http_client_response_body_get，直到收到**NX_WEB_HTTP_GET_DONE**或者其他非**NX_SUCCESS**的错误status。

**Comment by chengshuihang** [comment]
服务器响应包不足60字节，理论上调用nx_web_http_client_response_body_get一次就可以吧？要么成功，要么失败，但是并没有处理掉这个情况。下面截图是nx_web_http_client_response_body_get函数，我此时的client_ptr -> nx_web_http_client_state值为1，不满足条件。
![image](https://user-images.githubusercontent.com/45716763/174995466-b021588a-6525-4e06-a798-eff0007b382e.png)

**Comment by wenhui-xie** [comment]
1. 调用nx_web_http_client_response_body_get的次数和packet的payload无关，数据包有可能被分成多个小包。您可以检查一下nx_web_http_client_response_body_get返回的status吗？
2. “我此时的client_ptr -> nx_web_http_client_state值为1”，如果重新调用了nx_web_http_client_post_start_extended，这个state是会被重置的，您是何时读取该值？

**Comment by chengshuihang** [comment]
1.可以的。我后续会添加这个返回值检测
2.我没看懂。读取数据是在，服务器持续10多s没有收到客户端数据时，读取值的。在_nx_web_http_client_connect中，此时nx_web_http_client_state值为1，且不会变化
下面是nx_web_http_client_post_start_extended
![image](https://user-images.githubusercontent.com/45716763/175197028-77dc0aba-5fdc-4029-b38c-fa00da460825.png)
下面是_nx_web_http_client_connect代码
当client_ptr -> nx_web_http_client_state为1时，_nx_web_http_client_connect将返回错误，然后nx_web_http_client_post_start_extended直接退出，nx_web_http_client_state没有操作
`UINT  _nx_web_http_client_connect(NX_WEB_HTTP_CLIENT *client_ptr, NXD_ADDRESS *server_ip, UINT server_port, ULONG wait_option)

{

UINT        status;

#ifndef NX_WEB_HTTP_KEEPALIVE_DISABLE

    /* If keep-alive is true, the client is already connected to the server.  */
    if (client_ptr -> nx_web_http_client_keep_alive)
    {

        /* Clean up and reset the state.  */
        _nx_web_http_client_cleanup(client_ptr);

        if (nx_tcp_socket_state_wait(&(client_ptr -> nx_web_http_client_socket), NX_TCP_ESTABLISHED, 0) == NX_SUCCESS)
        {

            /* No need to reconnect.  */
            return(NX_SUCCESS);
        }
        else
        {

            /* Server disconnected the connection, need to reconnect.  */
            _nx_web_http_client_error_exit(client_ptr, wait_option);
        }
    }
#endif /* NX_WEB_HTTP_KEEPALIVE_DISABLE */

    /* Determine if the client is in a ready state.  */
    if (client_ptr -> nx_web_http_client_state != NX_WEB_HTTP_CLIENT_STATE_READY)
    {

        /* Reset the state.  */
        _nx_web_http_client_cleanup(client_ptr);
    }

    /* Attempt to bind the client socket.  */
    status =  nx_tcp_client_socket_bind(&(client_ptr -> nx_web_http_client_socket), NX_ANY_PORT, wait_option);

    /* Check status of the bind.  */
    if ((status != NX_SUCCESS) && (status != NX_ALREADY_BOUND))
    {

        /* Error binding to a port, return to caller.  */
        return(status);
    }

    /* Set the server IP and port. */
#ifdef FEATURE_NX_IPV6
    COPY_NXD_ADDRESS(server_ip, &(client_ptr -> nx_web_http_client_server_address));
#else
    client_ptr -> nx_web_http_client_server_address.nxd_ip_version = NX_IP_VERSION_V4;
    client_ptr -> nx_web_http_client_server_address.nxd_ip_address.v4 = server_ip -> nxd_ip_address.v4;
#endif

    client_ptr -> nx_web_http_client_connect_port = server_port;

    /* Connect to the HTTPS server with TCP.  */
    status = nxd_tcp_client_socket_connect(&(client_ptr -> nx_web_http_client_socket), server_ip,
                                             client_ptr -> nx_web_http_client_connect_port, wait_option);

    /* Check for connection status.  */
    if ((status != NX_SUCCESS) && (status != NX_IN_PROGRESS))
    {
    	nx_tcp_socket_disconnect(&(client_ptr -> nx_web_http_client_socket), wait_option);
        /* Error, unbind the port and return an error.  */
        nx_tcp_client_socket_unbind(&(client_ptr -> nx_web_http_client_socket));
    }

    return(status);
}`

**Comment by wenhui-xie** [comment]
”服务器响应包不足60字节，理论上调用nx_web_http_client_response_body_get一次就可以吧？要么成功，要么失败，但是并没有处理掉这个情况。下面截图是nx_web_http_client_response_body_get函数，**我此时的client_ptr -> nx_web_http_client_state值为1，不满足条件**。“
上一条回复的第2点主要是为了确认您之前说的**不满足条件**。在调用nx_web_http_client_response_body_get()之后，如果nx_web_http_client_state不为1，继续调用nx_web_http_client_post_start_extended()，在[_nx_web_http_client_cleanup()](https://github.com/azure-rtos/netxduo/blob/master/addons/web/nx_web_http_client.c#:~:text=the%20state.%20%20*/-,_nx_web_http_client_cleanup(client_ptr)%3B,-%7D)函数内会重置nx_web_http_client_state为1。因此如果您已经在nx_web_http_client_response_body_get()之后调用了nx_web_http_client_post_start_extended()，确实不满足条件。

您现在的问题是server发了fin包，client没有处理这个disconnet。但是在没有启用keep-alive的情况下，正常的流程应该是client在nx_web_http_client_response_body_get完成之后主动关闭连接。如果server提前发了fin包，client在nx_web_http_client_response_body_get的过程中也会因为收包失败而关闭连接。所以您这边先检查一下nx_web_http_client_response_body_get的返回值，以便进一步分析。

**Comment by chengshuihang** [comment]
好的，我看看如何修改代码，谢谢！

**Comment by bo-ms** [comment]
@chengshuihang closing, 如果有进一步的问题，可以创建新的issue。
