### ISSUE TITLE
Adding root certificates to trusted certificates does not work

### ISSUE THREAD

**Issue by rk3399** [azure-rtos/netxduo#112]
For example "github.com", if you just add the certificate of "DigiCert Global Root CA" to the trusted certificate, NETXDUO will report a certificate error when connecting to github.com, you must add the complete certificate of github.com to connect successfully

**Comment by rk3399** [comment]
Thanks, I am using nx_secure_tls_session_packet_buffer_set to allocate 40000 bytes of memory

> Hi @rk3399 , did you use `nx_secure_tls_remote_certificate_allocate` twice to allocate buffer for two server certificates or use `nx_secure_tls_session_packet_buffer_set` to set a large enough buffer to hold incoming TLS record plus certificate buffer?

Thanks, I am using nx_secure_tls_session_packet_buffer_set to allocate 40000 bytes of memory

**Comment by rk3399** [comment]
> Hi @rk3399 , did you use `nx_secure_tls_remote_certificate_allocate` twice to allocate buffer for two server certificates or use `nx_secure_tls_session_packet_buffer_set` to set a large enough buffer to hold incoming TLS record plus certificate buffer?

Thanks, I am using nx_secure_tls_session_packet_buffer_set to allocate 40000 bytes of memory

**Comment by TiejunMS** [comment]
Do you set packet buffer to 4000**0** bytes or 4000 bytes? I have created a sample project [here](https://github.com/TiejunMS/netxduo_projects/tree/main/issue_112) and NetX Duo is able to connect to github.com with root ca.

**Comment by TiejunMS** [comment]
我建议对比下这个[源文件](https://github.com/TiejunMS/netxduo_projects/blob/main/issue_112/main.c)里的和你本地的TLS初始化代码，看看有什么区别。上面提到的工程建议在GitHub的CodeSpace里直接打开运行。如果是需要本地运行的话可以自行编译docker image然后在docker里运行。

从你的调试信息看来，TLS的服务器证书没有正确的存储到TLS session里。首先请确保运行的是最新版本的NetX Duo 6.1.11。如果问题还存在的话，可以在[这里](https://github.com/azure-rtos/netxduo/blob/93aff552c9e85c3b96f7ae62d0cdf48649d641ea/nx_secure/src/nx_secure_tls_process_remote_certificate.c#L348)设置个断点，然后继续单步执行看看为什么packet_buffer无法用来存储服务器的两张证书。

**Comment by rk3399** [comment]
> 我建议对比下这个[源文件](https://github.com/TiejunMS/netxduo_projects/blob/main/issue_112/main.c)里的和你本地的TLS初始化代码，看看有什么区别。上面提到的工程建议在GitHub的CodeSpace里直接打开运行。如果是需要本地运行的话可以自行编译docker image然后在docker里运行。
> 
> 从你的调试信息看来，TLS的服务器证书没有正确的存储到TLS session里。首先请确保运行的是最新版本的NetX Duo 6.1.11。如果问题还存在的话，可以在[这里](https://github.com/azure-rtos/netxduo/blob/93aff552c9e85c3b96f7ae62d0cdf48649d641ea/nx_secure/src/nx_secure_tls_process_remote_certificate.c#L348)设置个断点，然后继续单步执行看看为什么packet_buffer无法用来存储服务器的两张证书。

是的，将netxduo升级后问题得以解决，谢谢
