### ISSUE TITLE
Nx_web_http_server_secure_configure() improper remote certificate list management

### ISSUE THREAD

**Issue by leobbditestcom** [azure-rtos/netxduo#113]
When there is more than one remote certificate being allocated, nx_web_http_server_secure_configure() attempts to re-add the same certificate to remote certificates list, because certificates are being indexed by session index instead of certificate index.  This problem went away when the following change was made to nx_tcpserver.c, line 533:

                //status = nx_secure_tls_remote_certificate_allocate(tls_session, remote_certificates[i],
                status = nx_secure_tls_remote_certificate_allocate(tls_session, remote_certificates[cert_count],

**Comment by wenhui-xie** [comment]
@leobbditestcom Thanks for reporting this issue, we will fix it in the next release.

**Comment by bo-ms** [comment]
@leobbditestcom closing, the bug fix is released in 6.1.12 now.
