### ISSUE TITLE
如何管理多个网络接口的设备

### ISSUE THREAD

**Issue by rk3399** [azure-rtos/netxduo#118]
我尝试使用nx_ip_create+nx_ip_interface_attach的方式，但是似乎不能为每个接口设置网关地址，使得不是每个接口都能和非同一网段的主机通信

**Comment by TiejunMS** [comment]
NetX目前只支持一个IPv4的默认网关。

**Comment by rk3399** [comment]
> NetX目前只支持一个IPv4的默认网关。

还是需要为每个接口调用nx_ip_create，这似乎有些麻烦

**Comment by rk3399** [comment]
> NetX目前只支持一个IPv4的默认网关。

还是需要为每个接口调用nx_ip_create吗？这似乎有些麻烦……

**Comment by TiejunMS** [comment]
请问能否分享下设置两个网关的使用场景？

**Comment by rk3399** [comment]
现在遇到的问题是我的设备上有两个网络接口，默认接口通过nx_ip_create设置静态ip地址192.168.0.101，从接口通过nx_ip_interface_attach设置静态地址192.168.0.102，然后设置了一个网关地址192.168.0.1。当默认接口未连接网关而从接口正常连接时，设备不能够通过从接口与外网通信

**Comment by TiejunMS** [comment]
谢谢分享这个使用场景，我们在后续迭代中会考虑这一块的支持。
