### ISSUE TITLE
Typo : August string : "Aud" => "Aug"

### ISSUE THREAD

**Issue by DoudFPV** [azure-rtos/netxduo#122]
August typo :"Aud" => "Aug"

https://github.com/azure-rtos/netxduo/blob/72dcde94184b9996894c4be3b4a5cafb2b448100/addons/sntp/nxd_sntp_client.c#L4909

**Comment by bo-ms** [comment]
Hi @DoudFPV Much thanks for reporting this issue to us, we will fix it.

**Comment by bo-ms** [comment]
Fixed it in 6.2.0 https://github.com/azure-rtos/netxduo/releases/tag/v6.2.0_rel
