### ISSUE TITLE
When MQTT connect failed,  how to retrieve error_number ?

### ISSUE THREAD

**Issue by DoudFPV** [azure-rtos/netxduo#128]
when nxd_mqtt_client_secure_connect() FAILED the function return NXD_MQTT_CONNECT_FAILURE instead of status.
https://github.com/azure-rtos/netxduo/blob/72dcde94184b9996894c4be3b4a5cafb2b448100/addons/mqtt/nxd_mqtt_client.c#L3941

In case of connexion error, is their a way to get the "error_number" (Return value of nx_secure_tls_session_start() and argument of _nx_secure_tls_map_error_to_alert()) ?

**Comment by bo-ms** [comment]
Hi @DoudFPV Thanks for reporting the issue, we will consider returning the TLS error number to application.
