### ISSUE TITLE
Bug : nx_ip_interface_status_check() 

### ISSUE THREAD

**Issue by DoudFPV** [azure-rtos/netxduo#133]
In nx_ip_interface_status_check() we don't check if driver entry pointer if is not NULL before calling it.

https://github.com/azure-rtos/netxduo/blob/a69a06e35da0ac763b363388f555b508b0cd84b7/common/src/nx_ip_interface_status_check.c#L188

https://github.com/azure-rtos/netxduo/blob/a69a06e35da0ac763b363388f555b508b0cd84b7/common/src/nx_ip_interface_status_check.c#L257

Note : after nx_ip_interface_detach(), this pointeur is set to NULL, so we should test it with something like : 
<img width="913" alt="image" src="https://user-images.githubusercontent.com/11795982/200337810-1531e7e7-11ea-4c2b-ae95-d14ce1b7cdd5.png">

**Comment by TiejunMS** [comment]
Thanks @DoudFPV ! We have fixed this issue and will be available in next release.
