### ISSUE TITLE
Server DUID parsing in DHCPV6 Advertise message fails

### ISSUE THREAD

**Issue by prarthana-13** [azure-rtos/netxduo#135]
![image](https://user-images.githubusercontent.com/76159538/200827709-c653b60d-7bc7-47d9-b150-1136186f4f50.png)

In server duid its looking for duid time field which doesnt exist in the received packet.
 This variable  is dhcpv6_ptr->nx_dhcpv6_client_duid.nx_duid_type = 1   and 
if (((index - 4) > length) || ((index - 4) < length))  check fails

We are using Netx version 5.7. Is this issue resolved in recent releases?

**Comment by bo-ms** [comment]
Closing, feel free to open new issue.
