### ISSUE TITLE
MDNS not support unicast response when UNICAST-RESPONSE bit was enable

### ISSUE THREAD

**Issue by laipochen** [azure-rtos/netxduo#140]
MDNS not support unicast response when Queries UNICAST-RESPONSE bit was enable.
The function is further explained in [RFC 6762](https://datatracker.ietf.org/doc/html/rfc6762#section-10.2)
The implement should be follow the RFC.

**Comment by wenhui-xie** [comment]
@laipochen Thanks for your report. We will take a look at this issue.

**Comment by wenhui-xie** [comment]
I have checked that our MDNS doesn't support unicast response for now.

**Comment by wenhui-xie** [comment]
Closing.
