### ISSUE TITLE
SFTP or FTPS support

### ISSUE THREAD

**Issue by bitwq** [azure-rtos/netxduo#141]
**Is your feature request related to a problem? Please describe.**
for secure file upload/download, SFTP or FTPs protocol support is needed.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TiejunMS** [comment]
Hi @bitwq , SFTP or FTPS are not on our roadmap. There are third party implementation such as wolfSSL: https://www.wolfssl.com/products/wolfssh/
