### ISSUE TITLE
Need help on using the iperf and network tools 

### ISSUE THREAD

**Issue by panneerc** [azure-rtos/netxduo#147]
**Describe the bug**

Please also mention any information which could help others to understand
the problem you're facing:
- What target device are you using? We are going to deploy on Azure WVD or AVD 

Need help on using the iperf to run on Azure container and the webpage on Clients to test the Network latency .

**Comment by TiejunMS** [comment]
If your device running Azure RTOS has a public IP address, then you can run both client and server test. If not, the device can run as client only. See network topology below. PC and device must be in the same network or at least PC should be able to access device. From PC browser, open http://10.0.0.2 (replace with actual IP address). Change the IP address of iperf server and start test.

![image](https://user-images.githubusercontent.com/50469179/216922021-4fbc1e8b-9a7a-4e16-a3b2-2e0b65e387ce.png)

**Comment by panneerc** [comment]
Hello @TiejunMS  Thanks for the Information. Do we need to install client on all VM machines ?
Because i am looking for the option like running iperf/Jperf on machine from web interface

**Comment by TiejunMS** [comment]
In above network topology, you only need to install iperf on Azure VM. For NetX running on device, the iperf application is already there.

**Comment by TiejunMS** [comment]
Closing.
