### ISSUE TITLE
Does netx duo support ipv6 DSCP?

### ISSUE THREAD

**Issue by shahab5** [azure-rtos/netxduo#159]
`nx_ip_packet_send` that takes type of service as input, but `nx_ipv6_packet_send` doesn't.

Why DSCP isn't supported for IPv6? Is this not an important feature to support?

Thanks,
Shahab

**Comment by TiejunMS** [comment]
@shahab5 , I would not say DSCP is not important. But unfortunately, it is not supported by NetX Duo yet. And we don't have a plan to support it in the near future. You are free to modify the source code in your local environment to support this feature.

**Comment by shahab5** [comment]
Thanks @TiejunMS for a quick response!
