### ISSUE TITLE
Does netxduo have a function to send a IPv6 RA message 

### ISSUE THREAD

**Issue by prarthana-13** [azure-rtos/netxduo#169]
Hi,
Does the netxduo have or support a function to send a IPv6 RA message . If not how can we be able to send a RA message in response to RS message .

**Comment by TiejunMS** [comment]
Sending IPv6 RA is not supported by NetXDuo. To send RA message, you can use API nxd_ip_raw_packet_send() to construct RA header. To receive RS message, set a raw packet filter by nx_ip_raw_packet_filter_set() to hijack RA message.

**Comment by shahab5** [comment]
HI @TiejunMS we see that DHCPv6 server https://github.com/azure-rtos/netxduo/blob/master/addons/dhcp/nxd_dhcpv6_server.c implementation is present in the NetxDuo, how does it work without the RA messages? Does the DHCPv6 implementation support Stateful DHCPv6? Please help to understand the implementation done for DHCPv6 Server in this file.

**Comment by TiejunMS** [comment]
@bo-ms , could you help with this question?

**Comment by bo-ms** [comment]
Hi @shahab5 DHCPv6 is stateful address autoconfiguration protocol for IPv6 ([RFC3315](https://datatracker.ietf.org/doc/html/rfc3315)), this protocol is a stateful counterpart to "IPv6 Stateless Adress Autoconfiguration (RA)" ([RFC2462](https://datatracker.ietf.org/doc/html/rfc2462)). Our DHCPv6 implementation supports stateful address autoconfiguration, DHCPv6 Client/Server uses Solicit, Advertise, Request, Confirm, etc to configure address and other information. If you want to use DHCPv6 in your network, you can refer to the sample https://github.com/azure-rtos/netxduo/blob/master/samples/demo_netxduo_dhcpv6.c

**Comment by prarthana-13** [comment]
Hi @TiejunMS @bo-ms , we have two observations w.r.t  RA message and ip configuration.

1.There is no RA message sent in response for RS 
![image](https://github.com/azure-rtos/netxduo/assets/76159538/a4195187-e4ec-405a-b0ad-20b3960b28da)

2. Even without RA message from server side, DHCPv6 handshake happens and an ip address is assigned.
![No RA](https://github.com/azure-rtos/netxduo/assets/76159538/448c31c1-4b58-4cd5-a760-565c34e4da1e)

Please do clarify this behaviour

**Comment by bo-ms** [comment]
Hi @prarthana-13 1. Your network (Router) may not support/enable IPv6 Stateless Address configuration. 2. DHCPv6 is completely independent feature, does not depend on RA/RS.

**Comment by shahab5** [comment]
@bo-ms, please refer to this page https://www.networkacademy.io/ccna/ipv6/stateful-dhcpv6
It described that  A, O, M flags of RA are required by the host to decide whether Stateless or Stateful DHCPv6 should be used.

The problem is with the NetX device when configured as DHCPv6 server, we see the Third party hosts are unable to configure the IP address, while they work fine with other DHCPv6 routers that send an RA in response to RS. We think not sending an RA is leading to IOP issues. Please help to mitigate this.

**Comment by bo-ms** [comment]
Hi @shahab5 Understood, router may combine/manage these features. But NetX just supports Stateful DHCPv6, as Tiejun suggested, you may implement the logic of processing RS and sending RA in your application. Thanks.
