### ISSUE TITLE
Hardfault when receiving ARP packets

### ISSUE THREAD

**Issue by dennisvbussel** [azure-rtos/netxduo#170]
I’m trying to run a TCP Echo server. My test application is able to obtain an IP via DHCP however hardfaults before I’m able to connect to the TCP socket when handling ARP packets. Below a snapshot:
![image](https://github.com/azure-rtos/netxduo/assets/51165557/46445078-c98a-447d-bfdc-dd7a72eb8886)

When I build the netxduo with NX_DISABLE_ARP_AUTO_ENTRY defined. The application is (sometimes) able to connect to the TCP socket however hardfaults either on socket_accept or socket_send when eventually using ARP. 
![image](https://github.com/azure-rtos/netxduo/assets/51165557/72f49017-0049-4f4e-b95b-6fc461ab1289)
![image](https://github.com/azure-rtos/netxduo/assets/51165557/4c35b2ee-cf6d-4066-bcb7-44baa2ea7d19)

When I take a look at the STM32H730VBTx CPU registers the sp is at 0x2404ffc8. Which is at the very end of the RAM_D1 region (base 0x24000000 and size 320KB (0x50000)). Could this indicate a memory leak?

**Toolchain**
STM32CubeIDE v1.12.1
ThreadX & NetXDuo v6.2.0_rel
STM32H730VBTx (Code execution from external flash in XIP mode)
DP83825I driver (own implementation forked from the lan8742 driver provided by ST)

**Comment by dennisvbussel** [comment]
Never mind.... 
Enabled the stack checker and the App TCP Thread stack seems to cause issues, after doubling it the issue seems to be resolved.

**Comment by TiejunMS** [comment]
Good to know your issue is resolved.
