### ISSUE TITLE
BSD and Cybersecurity issues

### ISSUE THREAD

**Issue by ChanakyaMacharla** [azure-rtos/netxduo#179]
Hi techies,

I am going through the NetX Duo documentation and source code,

1. As per the NetX Duo documentation, BSD APIs are not fully compatible, is there any future release planned to support all BSD calls
2. In source code We had observed critical and cybersecurity issues while running static code analysis tool on NetX Duo firmware. are you having same issue?

**Comment by TiejunMS** [comment]
Duplicate as support ticket 2306150030004913. Close this one to unify the discussion.

**Comment by hwmaier** [comment]
@TiejunMS Do you know when Microsoft is going to release patches or updates to address those cybersecurity issues?

**Comment by TiejunMS** [comment]
@hwmaier , just so you know, we haven't received issue report yet.
