### ISSUE TITLE
Issues in features of FTP

### ISSUE THREAD

**Issue by ChanakyaMacharla** [azure-rtos/netxduo#180]
Hi techies,

I am going through the NetX Duo documentation, In FTP section I have observed these issues

1. We are not able to see any information related to FTPS(implicit/explicit). is it supported?
2. In NetX FTP we understood that it is supporting only binary file format. Does it means NetX Duo’s FTP will not support utf-8 or something?

**Comment by bo-ms** [comment]
Hi @ChanakyaMacharla Thank you for asking. 
1. FTPS is not supported yet.
2. Currently, FTP just supports Binary file format.

**Comment by TiejunMS** [comment]
Duplicate as support ticket 2306150030004913. Close this one to unify the discussion.
