### ISSUE TITLE
NetX Duo with OS and without OS

### ISSUE THREAD

**Issue by ChanakyaMacharla** [azure-rtos/netxduo#182]
Hello techies,

I am going through the NetX Duo documentation and source code. I found that In NetX Duo core files like nx_ip_create.c, nxd_dhcp_client.c, nx_udp_socket_create.c are having direct ThreadX calls for timers and mutex. We understood that NetX Duo is tightly coupled with Azure RTOS/ThreadX. 

1. Is it possible to provide common abstraction layer to use NetX Duo with different RTOS instead of direct calls to ThreadX?
2. Is it supported for bare metal project? In other words, Can it be configured for bare metal project?

**Comment by TiejunMS** [comment]
Duplicate as support ticket 2306150030004913. Close this one to unify the discussion.
