### ISSUE TITLE
Netxduo is "blocked" after an error occured 

### ISSUE THREAD

**Issue by ZerAtaii** [azure-rtos/netxduo#188]
- What target device are you using?
LPC55S69
- Which version of Azure RTOS?
6.1
- What toolchain and environment?
arm-none-eabi-* + WSL

Hi,
I use Azure RTOS with the netxduo layer to manage TCP/IP sockets. The application exchanges a set of commands through netcat via "Windows sub Linux" on different ports (32071 to 32076) with an ethernet over USB protocol.
In my application, there are different communication buses, wifi / BLE / cellular network / IOT (through cellular or WIFI). When there is an error in one of the nx functions, for example in the "nx_tcp_server_socket_relisten" function, I get an error 0x23 which is NX_PORT_UNAVAILABLE. After that, it was impossible to continue exchanging through netcat on WSL, whatever the port. After a timeout of about 10 minutes, everything worked normally again.

![nxerror](https://github.com/azure-rtos/netxduo/assets/18376152/fb3a83e2-7a9b-4338-8401-ac54ff165617)

![nc](https://github.com/azure-rtos/netxduo/assets/18376152/aecafcf1-f0f9-4bf3-86e4-0d910148b0ad)

In fact, the various communication buses are totally multi-threaded but they all seem to refer to the same instance of Netxduo since all the ports are blocked simultaneously and then unblocked at the same time. 

Do you have any idea which parameter I can change to avoid this problem? 

Best regards,
Antoine

**Comment by TiejunMS** [comment]
0x23 should not be returned from `nx_tcp_server_socket_relisten`. Is the return status `0x35` instead? If so, it could be that the TCP server is not cleaned up before relisten. Try to call following APIs before it.
```
nx_tcp_socket_disconnect()
nx_tcp_server_socket_unaccept()
```

**Comment by TiejunMS** [comment]
Do you mean 10 minutes delay by calling relisten? If not, could you describe the question again, thanks!

**Comment by ZerAtaii** [comment]
In fact, sometimes i'm blocked for 29/30mins (i have measured it last week) and i don't know why, but one solution to this issue is to "deactivate/reactivate" my usb driver. The functions called are ux_slave_class_cdc_ecm_instance_activate and ux_slave_class_cdc_ecm_instance_deactivate, do you know how theses functions are triggered (HW or SF) ? Is there a way to reduce this strange 30mins delay to like 30secs / 1min?
![usb_IF](https://github.com/azure-rtos/netxduo/assets/18376152/6abec76a-a88f-48bd-aafe-abf3eb730439)

**Comment by TiejunMS** [comment]
I'm a little bit confused about the 'delay'. Where does it occur? In `nx_tcp_server_socket_relisten`, `nx_tcp_server_socket_accept` or somewhere else?

**Comment by ZerAtaii** [comment]
![nxerror](https://github.com/azure-rtos/netxduo/assets/18376152/32b56797-82b1-4fd1-850a-ab9e788e3f5f)
After getting "Host disconnect" from TCP socket, i tried to nx_tcp_socket_disconnect()/nx_tcp_server_socket_unaccept()/nx_tcp_server_socket_relisten() as you said and that's working (no more error). But i don't have any interrupts from clients even if i try many times before 29 mins.

**Comment by ZerAtaii** [comment]
And secondly, how can i trigger ux_slave_class_cdc_ecm_instance_activate and ux_slave_class_cdc_ecm_instance_deactivate from a software point of view?

**Comment by TiejunMS** [comment]
@xiaocq2001 , can you help with USBX questions?

**Comment by TiejunMS** [comment]
Closing as duplicate with https://github.com/azure-rtos/usbx/issues/114
