### ISSUE TITLE
https://altair.sony-semicon.com/technology/integrated-sim/


### ISSUE THREAD

**Issue by Sonyashines** [azure-rtos/netxduo#193]
**Is this request related to a particular hardware platform, SoC, board? Please describe.**
Describe in details the hardware support being requested and why this support benefits Azure RTOS.

**Describe why you are asking for this support?**
Describe why you are asking for this support.

If this is a new board or SoC, please state whether you are willing to maintain the Azure RTOS support together with you.

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the hardware here.

**Comment by bo-ms** [comment]
Closing due to invalid information.
