### ISSUE TITLE
[Question] "IoT device configuration" IotHub feature for firmware update sample

### ISSUE THREAD

**Issue by pesetskyps** [azure-rtos/netxduo#28]
There is example of implementation using Preview feature "Device Updates" [here](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-azure-real-time-operating-system)
Is there any example how to leverage "IoT device configuration" IotHub feature for firmware update?

**Comment by TiejunMS** [comment]
Are you looking for sample projects? If so, here is the link: https://github.com/azure-rtos/samples/tree/PublicPreview/ADU

**Comment by pesetskyps** [comment]
That is actually example bound to using Azure "Device Updates" service, I am looking for implementation of firmware update using  "IoT device configuration" . The link that you've post is actually the link that is inside the link that I posted in initial question. ADU example are tied to use device update service in Azure.

**Comment by hihigupt** [comment]
@pesetskyps just to confirm when you are referring to "IoT device configuration", do you are mean "device twin" ?

**Comment by pesetskyps** [comment]
well it levergaes the device twin, but I am talking about this specific tab in Iot Hub
![image](https://user-images.githubusercontent.com/6270100/114827232-1a4e5900-9dd1-11eb-82a8-a65d1e20bfb6.png)

**Comment by bo-ms** [comment]
Hi @pesetskyps  do you mean Device Update for IoT Hub, if so, the tab should be Device updates in IoT Hub, and [here ](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/) is the document about Device Update for IoT Hub.
![image](https://user-images.githubusercontent.com/50469338/114832446-133f3f00-9e01-11eb-9eb0-d3e83be6144c.png)

**Comment by pesetskyps** [comment]
No, Iot device configuration - please take a look at the video. 
https://www.youtube.com/watch?v=pZ9-TLE5RVI&ab_channel=MicrosoftDeveloper

**Comment by liydu** [comment]
@pesetskyps, the link you provided is a previous demo we created on top of MXChip board that demonstrates OTA using [Device Twins](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins) in IoT Hub. That was back in the era that Device Update service didn't exist. It should still work but no longer a recommended way to implement the OTA feature using Azure IoT.

So right now, we recommend to use the Azure RTOS and Device Update to build your OTA functionality on the device. You can check more details from: https://aka.ms/azrtos-device-update-preview

**Comment by bo-ms** [comment]
Closing this issue now, feel free to open the issue if you have further question.
