### ISSUE TITLE
CoAP addon missing

### ISSUE THREAD

**Issue by beriberikix** [azure-rtos/netxduo#3]
According to the [docs](https://docs.microsoft.com/en-us/azure/rtos/netx-duo/overview-netx-duo#coap), there should be a CoAP package. IIRC that has always been part of ThreadX NetX Duo.

**Comment by yuxin-azrtos** [comment]
CoAP will be available on GitHub by December 2020.

**Comment by PProvost** [comment]
Thanks. We're making an update to the docs to accurately represent what is there now and what will be coming soon. I'll close this once the docs are updated.

**Comment by PProvost** [comment]
Docs have been updated, so I'm closing this Issue. The expected release date is as @yuxin-azrtos mentioned above.
