### ISSUE TITLE
Support for HTTP version 1.1

### ISSUE THREAD

**Issue by shahab5** [azure-rtos/netxduo#32]
Hi,

The current code supports HTTP 1.0, is there any implementation available for HTTP 1.1?
If not, is there any plan? Can you please share the timeline?

Thanks,
Shahab

**Comment by TiejunMS** [comment]
Hi @shahab5 , are you looking for HTTP client for server? Do you have a requirement list for HTTP 1.1?

**Comment by shahab5** [comment]
Hi @TiejunMS ,

We want to use both HTTP 1.1 client and server implementations. Is there any timeline for this implementation? 

Thanks,
Shahab

**Comment by TiejunMS** [comment]
NetXDuo HTTP supports basic features of HTTP 1.1 client and server. Did you see any features not supported? Please take a look at addons/web.
