### ISSUE TITLE
Support for MQTT version 5.0

### ISSUE THREAD

**Issue by shahab5** [azure-rtos/netxduo#33]
Hi,

The MQTT client supports version 3.1.1 in the current codebase. 
Is there any plan or implementation to support version 5.0?

Thanks,
Shahab

**Comment by bo-ms** [comment]
Hi @shahab5 yes, we do have plan to support MQTT 5.0, but there is no timeline for now.

**Comment by hwmaier** [comment]
It has been a while since I asked this question. Is MQTT 5.0 now supported?

**Comment by bo-ms** [comment]
Hi @hwmaier thanks for asking, MQTT5.0 is not supported yet.

**Comment by hwmaier** [comment]
Thank you for the info. I was hoping there would be support for it on the horizon.
