### ISSUE TITLE
return error code

### ISSUE THREAD

**Issue by mapellil** [azure-rtos/netxduo#34]
Hello, in the NetXDuo file nxd_dhcp_client.c at line 387, 406, 432 the check is on NX_SUCCESS while it should be on TX_SUCCESS given the ThreadX API called.
Given that NX_SUCCESS = TX_SUCCESS = 0 the execution flow is not affected but in case an error is returned the wrong code is misleading.
Best regards

**Comment by bo-ms** [comment]
Hi @mapellil thank you for pointing this out, we will improve the code.
