### ISSUE TITLE
nx_tcpserver.c has diagnostic printf calls in code

### ISSUE THREAD

**Issue by hwmaier** [azure-rtos/netxduo#41]
There are several printf calls in file `addons/web/nx_tcpserver.c ` which probably either should not be in there (leftovers from debugging?) or should be wrapped in something like NX_DEBUG:

```
        if((status != NX_SUCCESS) && (status != NX_CONNECTION_PENDING))
        {
            printf("%d, %d\n", status, __LINE__);
            return NX_TCPSERVER_FAIL;
        }
 ```

**Comment by TiejunMS** [comment]
Thanks for your feedback! We will cleanup the debug information in the future.

**Comment by yuxin-azrtos** [comment]
Closing.
