### ISSUE TITLE
Is there any test suite to validate the NetX after porting to the target platform?

### ISSUE THREAD

**Issue by shahab5** [azure-rtos/netxduo#44]
Hi,

Is there any test suite that can be run to validate the NetX stack?
If it exists, can it be shared?

Thanks,
Shahab

**Comment by TiejunMS** [comment]
@yuxin-azrtos , could you help on this question?

**Comment by yuxin-azrtos** [comment]
@shahab5 Recommend that you run the iperf utility on the board.  Unless you modified NetX internals, in typical situations, the porting work only involves driver work.  iperf is a good utility that stress tests the driver layer porting work.

For NetX Duo, please use the version in our release: https://github.com/azure-rtos/netxduo/tree/master/utility/iperf
