### ISSUE TITLE
Question regarding FTP server and FileX disks

### ISSUE THREAD

**Issue by sdelcore** [azure-rtos/netxduo#45]
Hello! Thanks for all the great work on the project. I was wondering if there was any way you could use multiple FileX disks with one FTP server? I currently have a FLASH drive and a RAM drive and would like to be able to access them both from the same FTP server.

**Comment by bo-ms** [comment]
Hi @sdelcore, thanks for sharing your scenario, our FTP server does not support multiple disks yet, we will discuss this feature internally.

**Comment by yuxin-azrtos** [comment]
Closing this issue. Feel free to reopen if you have additional comments.
