### ISSUE TITLE
broker-less pubsub?

### ISSUE THREAD

**Issue by edbek** [azure-rtos/netxduo#5]
Are there any plans in the future to add the possibility of broker-less pubsub technology to netxduo, for example, nng (https://github.com/nanomsg/nng)?

**Comment by edbek** [comment]
Such a product as NNG is no more. Therefore, if the NNG appears on your network stack, then this will be a serious advance.

**Comment by yuxin-azrtos** [comment]
edbek, this is an interesting idea.  I did some search but couldn't find the spec on the serverless pubsub.  Can you point me the right direction? Thanks!

**Comment by edbek** [comment]
I can advise you to refer to the documentation for the ZeroMQ project https://zeromq.org/, since the NNG project itself was inspired by ZeroMQ.. The ZeroMQ project itself is very large for small embedded systems, but NNG is suitable for this.
Hope this helps you. Thank.

**Comment by yuxin-azrtos** [comment]
Thanks for the suggestion. We don't have plans to support ZeroMQ at this point.
