### ISSUE TITLE
CoAP standalone support from NetXDuo

### ISSUE THREAD

**Issue by srinivas1506** [azure-rtos/netxduo#51]
Hi All,

Recently I have started using NetxDuo to write few IoT applications and I was successful in writing MQTT standalone application by referring the sample provided in git repo.

Now my requirement is CoAP standalone support. If I search for CoAP its point to LWM2M which is based on CoAP. 
Could you please help me that how can I proceed with to get standalone CoAP implementation? Any pointers would be helpful to me.

Thanks,
Srinivas.

**Comment by yuxin-azrtos** [comment]
@srinivas1506 thanks for reaching out to the Azure RTOS team.  Standalone CoAP is not yet available.

**Comment by srinivas1506** [comment]
@yuxin-azrtos,

Thanks for the information. By any chance are your team planning to integrate CoAP near time?

If I have to try CoAP on NetXDuo, how can I proceed? Please let me know if there are any pointers or inputs or git repo links to go ahead.

Thanks in advance,
Srinivas.

**Comment by hwmaier** [comment]
I just came across this comment here https://github.com/azure-rtos/netxduo/issues/3#issuecomment-632793953 where CoAP was announced to be available by December 2020. Is there an update of the release date?

**Comment by yuxin-azrtos** [comment]
@srinivas1506, @hwmaier we don't have plans for CoAP at this point (there were some discussions a while back but CoAP was not prioritized).  Please reach out to azure-rtos-support@microsoft.com and we can further help you with your needs.

**Comment by yuxin-azrtos** [comment]
CoAP is built into the lwM2M stack. However it is not exposed as a standalone module.
