### ISSUE TITLE
Multiple DHCP clients on multiple interfaces issue 

### ISSUE THREAD

**Issue by marianoizzi** [azure-rtos/netxduo#54]
Hi, I'm using NetX Duo with two ethernet interfaces, each with its IP instance (named ip_0 & ip_1).
These IP instances have a DHCP client each (dhcp_client_0 & dhcp_client_1).
After creating and starting both DHCP clients only the last one created works, this is because the receive notification function
uses only the DHCP instance pointed by **_nx_dhcp_created_ptr**, and doesn't look for the interface's specific one:

```
VOID _nx_dhcp_udp_receive_notify(NX_UDP_SOCKET *socket_ptr)
{
    NX_PARAMETER_NOT_USED(socket_ptr);

    /* Set the data received event flag.  */
    tx_event_flags_set(&(_nx_dhcp_created_ptr -> nx_dhcp_events), NX_DHCP_CLIENT_RECEIVE_EVENT, TX_OR);
}
```

A possible fix that worked for me could be:
(This is just to show the idea, I used some **externs** to access my two IP/DHCP instances)
```
extern NX_IP ip_0;
extern NX_DHCP dhcp_client_0;
extern NX_IP ip_1;
extern NX_DHCP dhcp_client_1;
...
VOID _nx_dhcp_udp_receive_notify(NX_UDP_SOCKET *socket_ptr)
{
    NX_PARAMETER_NOT_USED(socket_ptr);

    if(socket_ptr->nx_udp_socket_ip_ptr == &ip_0)
    {
      tx_event_flags_set(&(dhcp_client_0.nx_dhcp_events), NX_DHCP_CLIENT_RECEIVE_EVENT, TX_OR);
    }
    else if(socket_ptr->nx_udp_socket_ip_ptr == &ip_1)
    {
      tx_event_flags_set(&(dhcp_client_1.nx_dhcp_events), NX_DHCP_CLIENT_RECEIVE_EVENT, TX_OR);
    }    
}
```
Cheers

**Comment by marianoizzi** [comment]
Thanks @bo-ms, just tested it and it works as expected.
You may close the issue.

**Comment by bo-ms** [comment]
Thanks @marianoizzi, we will fix it internally, and this bug fix will be in next release.
