### ISSUE TITLE
nx_tcpserver_tls_setup() : do not enable elliptic curve

### ISSUE THREAD

**Issue by DoudFPV** [azure-rtos/netxduo#56]
nx_tcpserver_tls_setup() works well for RSA key but not with EC

I found nx_secure_tls_ecc_initialize() call is missing.

My workaround is :
<img width="1701" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/11795982/139068912-92dbe09a-c34b-43f6-8332-d8376b82686a.png">

**Comment by DoudFPV** [comment]
I re-open this issue because it seems not fix in netXduo 6.1.10

**Comment by wenhui-xie** [comment]
@DoudFPV I have added an API to support ECC configuration. Could you leave your email address so that I can email you the patch files and sample code? And It would be helpful if you can give us your feedback about the new API.

**Comment by DoudFPV** [comment]
edouard.
malot
gmail.com

(I will delete msg after you get it)

**Comment by wenhui-xie** [comment]
@DoudFPV Got it.

**Comment by DoudFPV** [comment]
I didn't got your mail yet (don't forget "." between first name and family name)

**Comment by wenhui-xie** [comment]
@DoudFPV I have sent the email. Please check. Thanks.
