### ISSUE TITLE
not find nx_ipsec.h  file

### ISSUE THREAD

**Issue by linuxZS** [azure-rtos/netxduo#58]
when i open NX_IPSEC_ENABLE switch, it build error.  
../common/src/nx_icmp_interface_ping6.c:40:10: fatal error: nx_ipsec.h: No such file or directory

**Comment by TiejunMS** [comment]
@linuxZS thanks for reaching out to the Azure RTOS team. IPsec is not yet available. Please disable it in your project.

**Comment by Kabbah** [comment]
Any news on IPsec? As of today, `nx_ipsec.h` is still not available, even though IPsec is listed as a library feature.

![NetXDuo Features](https://github.com/eclipse-threadx/netxduo/blob/6c8e9d1c95d71bd4b313e1cc37d8f8841543b248/docs/netx-duo-features.png?raw=true)

**Comment by dortainlu** [comment]
When will it be available, and is there a roadmap for IPSec?
