### ISSUE TITLE
Typo in DHCP documentation

### ISSUE THREAD

**Issue by josesimoes** [azure-rtos/netxduo#62]
Missing `_` in https://docs.microsoft.com/en-us/azure/rtos/netx-duo/netx-duo-dhcp-client/chapter3?source=docs#nx_dhcp_-force_renew

![image](https://user-images.githubusercontent.com/1881520/145835541-4ea5da49-689d-4a5d-b617-7fe4cf65662f.png)

**Comment by TiejunMS** [comment]
@josesimoes , thanks for catching the typo. We will fix it soon!

**Comment by wenhui-xie** [comment]
Fixed at PR: https://github.com/MicrosoftDocs/rtos-docs-pr/pull/401

**Comment by bo-ms** [comment]
Closing
