### ISSUE TITLE
PPP with ipv6?

### ISSUE THREAD

**Issue by zhengjianxing** [azure-rtos/netxduo#70]
hello,Does the current netxduo version support PPP IPV6 and 4G module communication?
thanks.

**Comment by bo-ms** [comment]
Hi @zhengjianxing NetX Duo PPP supports IPv4, but does not support IPv6 yet. PPP can work on 4G module, but users need to port the PPP send and receive function over 4G, refer to: https://github.com/azure-rtos/netxduo/blob/master/samples/demo_netx_ppp.c#L324-L336

**Comment by bo-ms** [comment]
Closing it, feel free to reopen if you have further issue.
