### ISSUE TITLE
How to use Ipv6 addresses[not bug]

### ISSUE THREAD

**Issue by CYG01571** [azure-rtos/netxduo#71]
Hi!

Is there a good example of a client application that can get an IPv6 IP address from RA or DHCPv6 and communicate with a server in an environment where IPv4 and IPv6 coexist?

This is my first time dealing with IPv6 addresses, so I'm wondering where to start.

I've confirmed that RA packet is coming from radvd service by wireshark, but the callback function I registered by nxd_ipv6_address_change_notify() is not being notified.

I use Renesas Synergy system(S7G2).
Please help me.

Best Regards.

**Comment by TiejunMS** [comment]
Closed. Feel free to reopen if you have further issues.
