### ISSUE TITLE
SNMP Agent Enterprise ID support

### ISSUE THREAD

**Issue by hmckinlay** [azure-rtos/netxduo#75]
The agent doesn't seem to handle enterprise OIDs larger than 127.

1) Please confirm this is the case?
2) Is this on the roadmap?

In my opinion the whole SNMP module is useless to the vast majority of businesses unless you have this and tables.

**Comment by wenhui-xie** [comment]
Hi @hmckinlay, we have fixed an issue of retrieving the object ID larger than 127. This fix will be in the next release 6.1.10. Please leave your email address if you need the patch fixes for validation.

**Comment by wenhui-xie** [comment]
Close as Azure RTOS 6.1.10 is released. Feel free to reopen this issue if the latest code can't fix your issue.
