### ISSUE TITLE
Question : Is MQTT QOS=2 support planned?

### ISSUE THREAD

**Issue by DoudFPV** [azure-rtos/netxduo#76]
Is MQTT QOS=2 support planned?
(If yes any idea of the planning ?)

**Comment by TiejunMS** [comment]
@DoudFPV , we don't have plan to support QoS2 at the moment. Could you share your use case which requires QoS2? If there are more and more requests to support QoS2 in the future, we will plan to do it.

**Comment by DoudFPV** [comment]
@TiejunMS not sure we really need it (QoS1 might be enough).
The most critical case will be when we subscribe to a TOPIC and make an action when the value change, we worry to execute the action twice.

**Comment by TiejunMS** [comment]
For this case, a local variable to track the value change is a cheaper solution compared to QoS2, while QoS2 is a generic solution to avoid message duplication.
