### ISSUE TITLE
Question: Tagged VLAN support

### ISSUE THREAD

**Issue by sada1410** [azure-rtos/netxduo#79]
Hello, 

I would like to use Azure RTOS and the NetX Duo stack for a Profinet IO device. 

Will _VLAN (IEEE 802.1Q)_ be supported in the future? 

Thank you very much in advance. 

Best regards, 
Sada1410

**Comment by TiejunMS** [comment]
@sada1410 , VLAN support will likely be available next year.

**Comment by TiejunMS** [comment]
@rsmgnu, the rough estimation will be the end of this year or early next year.

**Comment by rcharb1** [comment]
Hello @TiejunMS ,
It does not seem that VLAN had been implemented yet. Is there any time estimation for that?
Thanks!
