### ISSUE TITLE
MQTT publish crashes

### ISSUE THREAD

**Issue by pawelkub** [azure-rtos/netxduo#80]
Im working on the project in which I use ThreadX and NetXduo with mqtt client.
I have one thread (M) in which I receive mqtt data and send response for them.
In other two threads (X and Y) Im sending telemetry data via mqtt.

I use the same publish mqtt API function where I use mutex to protect access to mqtt client object for sending mqtt data for whole system. 

Everything works correctly for a while (for example 50k published messages, but the exachanged messages number are not constant), but after that I get a communication error.
One of the thread, i.e. X stucks on forever-loop when publishing mqtt telemetry. 

It stucks in function _nx_ip_header_add() on 111 line:

```
/* Assert prepend pointer is no less than data start pointer.  */
/*lint -e{946} suppress pointer subtraction, since it is necessary. */
NX_ASSERT(packet_ptr -> nx_packet_prepend_ptr >= packet_ptr -> nx_packet_data_start);
```

After that the IP instance thread stuck, and I got mqtt disconnecting.

![image](https://user-images.githubusercontent.com/28606617/155333681-813d9136-176b-4cc0-bf97-021ee8d26e22.png)

**Comment by TiejunMS** [comment]
Hi @pawelkub , could you provide the version number from nx_api.h? It usually looks like 6.1.x. The call stack shows the packet struct is corrupted. Here are quick test you can do.
1. Increase stack size.
2. Upgrade AzureRTOS to latest version.

For thread suspends on _nx_ip_header_add, could you provide the data of nx_packet_prepend_ptr, nx_packet_data_start, nx_packet_append_ptr, nx_packet_data_end and nx_packet_length from packet_ptr?

**Comment by pawelkub** [comment]
Hi @TiejunMS, thanks for leply,

I used versions 6.1.7 of netxduo and threadx.
Update to latest 6.1.10 version doesn't help unfortunately.

Should I increase stack of thread which call mqtt publish function (in this case pms_thread) or mqtt client thread or IP instance thread?

packet_ptr data dump:
![image](https://user-images.githubusercontent.com/28606617/155504041-c51010e4-f9f7-413b-9b49-48d05f0334e7.png)

**Comment by TiejunMS** [comment]
The packet is set incorrectly somehow. To figure out what happened, are you aware if X thread stuck first or communication error occurs first?

**Comment by TiejunMS** [comment]
Close as no response.
