### ISSUE TITLE
Using NetXDuo PPP with TX CMSIS wrapper

### ISSUE THREAD

**Issue by dsilva-vd** [azure-rtos/netxduo#84]
Hi,

I'm on an STM32 micro platform and trying to adapt ST's cellular FW package to use NetX PPP instead of LwIP PPP.  

The ST cellular FW package uses CMSIS v1 API (based on FreeRTOS) and I know that ThreadX has a CMSIS wrapper. My question is if I use the ThreadX CMSIS wrapper to convert the threads for AT commands and cellular call setup can I mix those with Thread X native calls for things like the PPP and other functionality (i.e. Cloud, etc.)? 

Is there an example of my intended functionality I can refer to? I've seen the Tx_CMSIS wrapper projects made available by STM as part of their CUBE packages.

Thanks

**Comment by TiejunMS** [comment]
Close this issue as duplicated from https://docs.microsoft.com/en-us/answers/questions/757118/build-azrtos-with-cmsis-rtos-v2-or-use-threadx-cal.html

Hi @dsilva-vd , have you contacted ST for their schedule?
