### ISSUE TITLE
Question : DTLS and renegociation openssl v3

### ISSUE THREAD

**Issue by DoudFPV** [azure-rtos/netxduo#85]
nexduo works well as DTLS 1.2 server with Openssl v1.

With Openssl V3, renegotiation is required (rfc5746).
Are there any plans to add renegotiation on the DTLS server in a future release?

**Comment by TiejunMS** [comment]
Hi @DoudFPV , I have put this feature request in our internal backlogs, tentatively targeting Oct release.  Is there a workaround for openssl v3 without renegotiation extension?

**Comment by DoudFPV** [comment]
@TiejunMS Thanks.

For openssl@3,  yes, there is option _-legacy_renegotiation_ :   
`./openssl s_client -connect 192.168.1.22:5684 -legacy_renegotiation  -dtls -cipher PSK-AES128-GCM-SHA256 -psk XXXXX
`

**Comment by TiejunMS** [comment]
It is good know. I will close this issue. Feel free to reopen it.
