### ISSUE TITLE
sample_azure_iot_embedded_sdk_with_retry.c returns MQTT CONNECT FAIL status:65541

### ISSUE THREAD

**Issue by dsilva-vd** [azure-rtos/netxduo#86]
NETXDUO 6.1.7 - Tied to latest NETX distributed by STM32Cube IDE.

Using sample_azure_iot_embedded_sdk_with_retry.c I am consistently getting MQTT CONNECT FAIL status:65541 (0x10005) when trying to connect to my IOT Hub. The IOT hub is available as other clients (Python Azure SDK) can connect to the Hub).  Is there a way to turn on more debugging or some idea of where to start debugging this. 

Nx_SNTP_Client application started..
STM32 IpAddress: XXX.XXX.XXX.XXX 
SNTP client connected to NTP server : < ca.pool.ntp.org > 

SNTP update :
Mar 23, 2022 22:8:18.859 UTC 

23-03-2022 / 22:08:18
[INFO] Azure IoT Security Module has been enabled, status=0
IoTHub Host Name: Myazurehub.azure-devices.net; Device ID: mydevice.
[ERROR] IoTHub client connect fail: MQTT CONNECT FAIL status: 65541
Disconnected from IoTHub!: error code = 0x00010005
Failed on nx_azure_iot_hub_client_connect!
reconnecting iothub, after backoff
[ERROR] IoTHub client connect fail: MQTT CONNECT FAIL status: 65541
Disconnected from IoTHub!: error code = 0x00010005
reconnecting iothub, after backoff
[ERROR] IoTHub client connect fail: MQTT CONNECT FAIL status: 65541
Disconnected from IoTHub!: error code = 0x00010005
reconnecting iothub, after backoff

**Comment by dsilva-vd** [comment]
I have also  tried the secondary SAS key and the results are the same.

**Comment by dsilva-vd** [comment]
I have attached my app_netxduo.c file which sets up the IP instance and SNTP client before calling the sample_entry.

`
/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    app_netxduo.c
  * @author  MCD Application Team
  * @brief   NetXDuo applicative file
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2021 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "app_netxduo.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "nx_ip.h"
#include "stm32f4xx_hal_rtc.h"

#include "nx_secure_tls_api.h"
#include <time.h>
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */
TX_THREAD AppMainThread;
TX_THREAD AppSNTPThread;
TX_THREAD AppIoTClientThread;

TX_SEMAPHORE Semaphore;

NX_PACKET_POOL           AppPool;

NX_IP                    IpInstance;
NX_DHCP                  DhcpClient;
NX_DNS                   DnsClient;
NX_SNTP_CLIENT           SntpClient;

TX_EVENT_FLAGS_GROUP     SntpFlags;

ULONG                    IpAddress;
ULONG                    NetMask;

CHAR                     buffer[64];

UCHAR                    *pointer;


struct tm timeInfos;
/* RTC handler declaration */
RTC_HandleTypeDef RtcHandle;
/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
static UINT kiss_of_death_handler(NX_SNTP_CLIENT *client_ptr, UINT KOD_code);
static void display_rtc_time(RTC_HandleTypeDef *hrtc);
static void rtc_time_update(NX_SNTP_CLIENT *client_ptr);
static UINT unix_time_get(ULONG *unix_time);
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN PV */
/* set the SNTP network interface to the primary interface. */
UINT  iface_index =0;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN PFP */
static VOID App_Main_Thread_Entry(ULONG thread_input);
static VOID App_SNTP_Thread_Entry(ULONG thread_input);
static VOID App_IoT_Client_Thread_Entry(ULONG thread_input);

static VOID ip_address_change_notify_callback(NX_IP *ip_instance, VOID *ptr);
static VOID time_update_callback(NX_SNTP_TIME_MESSAGE *time_update_ptr, NX_SNTP_TIME *local_time);

VOID sample_entry(NX_IP *ip_ptr, NX_PACKET_POOL *pool_ptr, NX_DNS *dns_ptr, UINT (*unix_time_callback)(ULONG *unix_time));
//UINT azure_iot_nx_client_entry(
//NX_IP* ip_ptr, NX_PACKET_POOL* pool_ptr, NX_DNS* dns_ptr, UINT (*unix_time_callback)(ULONG* unix_time));
/* USER CODE END PFP */
/**
  * @brief  Application NetXDuo Initialization.
  * @param memory_ptr: memory pointer
  * @retval int
  */
UINT MX_NetXDuo_Init(VOID *memory_ptr)
{
  UINT ret = NX_SUCCESS;
  TX_BYTE_POOL *byte_pool = (TX_BYTE_POOL*)memory_ptr;

  /* USER CODE BEGIN MX_NetXDuo_MEM_POOL */
  /* USER CODE END MX_NetXDuo_MEM_POOL */

  /* USER CODE BEGIN MX_NetXDuo_Init */
  printf("Nx_SNTP_Client application started..\r\n");
  
  CHAR *pointer;
  
  /* Allocate the memory for packet_pool.  */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer,  NX_PACKET_POOL_SIZE, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }
  
  /* Create the Packet pool to be used for packet allocation */
  ret = nx_packet_pool_create(&AppPool, "Main Packet Pool", PAYLOAD_SIZE, pointer, NX_PACKET_POOL_SIZE);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Allocate the memory for Ip_Instance */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer, 4 * DEFAULT_MEMORY_SIZE, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }
  
  /* Create the main NX_IP instance */
  ret = nx_ip_create(&IpInstance, "Main Ip instance", NULL_ADDRESS, NULL_ADDRESS, &AppPool, nx_stm32_eth_driver,
                     pointer, 4 * DEFAULT_MEMORY_SIZE, DEFAULT_MAIN_PRIORITY);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }

  /* create the DHCP client */
  ret = nx_dhcp_create(&DhcpClient, &IpInstance, "DHCP Client");
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Allocate the memory for ARP */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer, ARP_MEMORY_SIZE, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }
  
  /* Enable the ARP protocol and provide the ARP cache size for the IP instance */
  ret = nx_arp_enable(&IpInstance, (VOID *)pointer, ARP_MEMORY_SIZE);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Enable the ICMP */
  ret = nx_icmp_enable(&IpInstance);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Enable the UDP protocol required for  DHCP communication */
  ret = nx_udp_enable(&IpInstance);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
 
    /* Enable the TCP protocol */
  ret = nx_tcp_enable(&IpInstance);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Allocate the memory for main thread   */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer, MAIN_THREAD_MEMORY, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }
  
  /* Create the main thread */
  ret = tx_thread_create(&AppMainThread, "App Main thread", App_Main_Thread_Entry, 0, pointer, MAIN_THREAD_MEMORY,
                         DEFAULT_MAIN_PRIORITY, DEFAULT_MAIN_PRIORITY, TX_NO_TIME_SLICE, TX_AUTO_START);
  
  if (ret != TX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Allocate the memory for SNTP client thread   */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer, SNTP_CLIENT_THREAD_MEMORY, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }
  
  /* Initialize TLS.  */
  nx_secure_tls_initialize();

  /* create the SNTP client thread */
  ret = tx_thread_create(&AppSNTPThread, "App SNTP Thread", App_SNTP_Thread_Entry, 0, pointer, SNTP_CLIENT_THREAD_MEMORY,
                         DEFAULT_PRIORITY, DEFAULT_PRIORITY, TX_NO_TIME_SLICE, TX_DONT_START);
  
  if (ret != TX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
    
  /* Create the event flags. */
  ret = tx_event_flags_create(&SntpFlags, "SNTP event flags");

  /* Check for errors */
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* set DHCP notification callback  */
  tx_semaphore_create(&Semaphore, "DHCP Semaphore", 0);

#if 0
  /* Allocate the memory for IoT client thread   */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer, IOT_CLIENT_THREAD_MEMORY, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }


  /* create the SNTP client thread */
  ret = tx_thread_create(&AppIoTClientThread, "App IoT Client Thread", App_IoT_Client_Thread_Entry, 0, pointer, IOT_CLIENT_THREAD_MEMORY,
                         DEFAULT_PRIORITY, DEFAULT_PRIORITY, TX_NO_TIME_SLICE, TX_DONT_START);

  if (ret != TX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
#endif

  /* USER CODE END MX_NetXDuo_Init */

  return ret;
}

/* USER CODE BEGIN 1 */

/**
* @brief  ip address change callback.
* @param ip_instance: NX_IP instance
* @param ptr: user data
* @retval none
*/
static VOID ip_address_change_notify_callback(NX_IP *ip_instance, VOID *ptr)
{
  /* release the semaphore as soon as an IP address is available */
  tx_semaphore_put(&Semaphore);
}

/**
* @brief  Main thread entry.
* @param thread_input: ULONG user argument used by the thread entry
* @retval none
*/
static VOID App_Main_Thread_Entry(ULONG thread_input)
{
  UINT ret;
  
  ret = nx_ip_address_change_notify(&IpInstance, ip_address_change_notify_callback, NULL);
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
  ret = nx_dhcp_start(&DhcpClient);
  
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
  /* wait until an IP address is ready */
  if(tx_semaphore_get(&Semaphore, TX_WAIT_FOREVER) != TX_SUCCESS)
  {
    Error_Handler();
  }
  
  ret = nx_ip_address_get(&IpInstance, &IpAddress, &NetMask);
    
  if (ret != TX_SUCCESS)
  {
    Error_Handler();
  }
  
  PRINT_IP_ADDRESS(IpAddress);
 
  /* the network is correctly initialized, start the TCP server thread */
  tx_thread_resume(&AppSNTPThread);
  
  /* this thread is not needed any more, we relinquish it */
  tx_thread_relinquish();
  
  return;
}

/**
* @brief  DNS Create Function.
* @param dns_ptr
* @retval ret
*/
UINT dns_create(NX_DNS *dns_ptr)
{
  UINT ret = NX_SUCCESS;

  /* Create a DNS instance for the Client */
  ret = nx_dns_create(dns_ptr, &IpInstance, (UCHAR *)"DNS Client");
  
  if (ret)
  {
    Error_Handler();
  }
  
  /* Initialize DNS instance with the DNS server Address */
  ret = nx_dns_server_add(dns_ptr, DNS_SERVER_ADDRESS);
  if (ret)
  {
    Error_Handler();
  }
  
  return ret;
}

/**
* @brief  SNTP thread entry.
* @param thread_input: ULONG user argument used by the thread entry
* @retval none
*/
/* Define the client thread.  */
static void App_SNTP_Thread_Entry(ULONG info)
{
  UINT ret;
  RtcHandle.Instance = RTC;
  ULONG  seconds, fraction;
  ULONG  events = 0;
  UINT   server_status;
  NXD_ADDRESS sntp_server_ip;
  NX_PARAMETER_NOT_USED(info);
  
  sntp_server_ip.nxd_ip_version = 4;
  
  /* Create a DNS client */
  ret = dns_create(&DnsClient);
  
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
  /* Look up SNTP Server address. */
  ret = nx_dns_host_by_name_get(&DnsClient, (UCHAR *)SNTP_SERVER_NAME, 
                                &sntp_server_ip.nxd_ip_address.v4, DEFAULT_TIMEOUT);
  
    /* Check for error. */
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
   /* Create the SNTP Client */
  ret =  nx_sntp_client_create(&SntpClient, &IpInstance, iface_index, &AppPool, NULL, kiss_of_death_handler, NULL);
  
  /* Check for error. */
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
  /* Setup time update callback function. */
   nx_sntp_client_set_time_update_notify(&SntpClient, time_update_callback);
  
  /* Use the IPv4 service to set up the Client and set the IPv4 SNTP server. */
  ret = nx_sntp_client_initialize_unicast(&SntpClient, sntp_server_ip.nxd_ip_address.v4);
  
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
  /* Run whichever service the client is configured for. */
  ret = nx_sntp_client_run_unicast(&SntpClient);
  
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  else 
  {
    PRINT_CNX_SUCC();
  }
  
  /* Wait for a server update event. */
  tx_event_flags_get(&SntpFlags, SNTP_UPDATE_EVENT, TX_OR_CLEAR, &events, PERIODIC_CHECK_INTERVAL);
  
  if (events == SNTP_UPDATE_EVENT)
  {
    /* Check for valid SNTP server status. */
    ret = nx_sntp_client_receiving_updates(&SntpClient, &server_status);
    
    if ((ret != NX_SUCCESS) || (server_status == NX_FALSE))
    {
      /* We do not have a valid update. */
      Error_Handler();
    }
    /* We have a valid update.  Get the SNTP Client time.  */
    ret = nx_sntp_client_get_local_time_extended(&SntpClient, &seconds, &fraction, NX_NULL, 0);
    
    ret = nx_sntp_client_utility_display_date_time(&SntpClient,buffer,64);
    
    if (ret != NX_SUCCESS)
    {
      printf("Internal error with getting local time 0x%x\r\n", ret);
      Error_Handler();
    }
    else
    {
      printf("\r\nSNTP update :\r\n");
      printf("%s\r\n\n",buffer);
    }
  }
  else
  {
    Error_Handler();
  }
  
  /* Set Current time from SNTP TO RTC */
  rtc_time_update(&SntpClient);
  
  /* We can stop the SNTP service if for example we think the SNTP server has stopped sending updates */
  ret = nx_sntp_client_stop(&SntpClient);
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
  /* When done with the SNTP Client, we delete it */
  ret = nx_sntp_client_delete(&SntpClient);
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
  /* Toggling LED after a success Time update */
  //while(1)
  //{
    /* Display RTC time each second  */
    //display_rtc_time(&RtcHandle);
    //BSP_LED_Toggle(LED1);
    /* Delay for 1s */
    //tx_thread_sleep(100);
  //}

  display_rtc_time(&RtcHandle);
  BSP_LED_Toggle(LED1);
  /* the network is correctly initialized, start the TCP server thread */
  //tx_thread_resume(&AppIoTClientThread);

  /* this thread is not needed any more, we relinquish it */
  //tx_thread_relinquish();
  sample_entry(&IpInstance, &AppPool, &DnsClient, unix_time_get);
}

/**
* @brief  IoT client thread entry.
* @param thread_input: ULONG user argument used by the thread entry
* @retval none
*/
/* Define the IoT client thread.  */
static VOID App_IoT_Client_Thread_Entry(ULONG thread_input)
{
  UNUSED(thread_input);

  /* Initialize TLS.  */
  //nx_secure_tls_initialize();

  //sample_entry(&IpInstance, &AppPool, &DnsClient, unix_time_get);
}


/* This application defined handler for handling a Kiss of Death packet is not
required by the SNTP Client. A KOD handler should determine
if the Client task should continue vs. abort sending/receiving time data
from its current time server, and if aborting if it should remove
the server from its active server list.

Note that the KOD list of codes is subject to change. The list
below is current at the time of this software release. */

static UINT kiss_of_death_handler(NX_SNTP_CLIENT *client_ptr, UINT KOD_code)
{
  UINT    remove_server_from_list = NX_FALSE;
  UINT    status = NX_SUCCESS;
  
  NX_PARAMETER_NOT_USED(client_ptr);
  
  /* Handle kiss of death by code group. */
  switch (KOD_code)
  {
    
  case NX_SNTP_KOD_RATE:
  case NX_SNTP_KOD_NOT_INIT:
  case NX_SNTP_KOD_STEP:
    
    /* Find another server while this one is temporarily out of service.  */
    status =  NX_SNTP_KOD_SERVER_NOT_AVAILABLE;
    
    break;
    
  case NX_SNTP_KOD_AUTH_FAIL:
  case NX_SNTP_KOD_NO_KEY:
  case NX_SNTP_KOD_CRYP_FAIL:
    
    /* These indicate the server will not service client with time updates
    without successful authentication. */
    
    remove_server_from_list =  NX_TRUE;
    
    break;
    
    
  default:
    
    /* All other codes. Remove server before resuming time updates. */
    
    remove_server_from_list =  NX_TRUE;
    break;
  }
  
  /* Removing the server from the active server list? */
  if (remove_server_from_list)
  {
    
    /* Let the caller know it has to bail on this server before resuming service. */
    status = NX_SNTP_KOD_REMOVE_SERVER;
  }
  
  return status;
}

/* This application defined handler for notifying SNTP time update event.  */
static VOID time_update_callback(NX_SNTP_TIME_MESSAGE *time_update_ptr, NX_SNTP_TIME *local_time)
{
  NX_PARAMETER_NOT_USED(time_update_ptr);
  NX_PARAMETER_NOT_USED(local_time);
  
  tx_event_flags_set(&SntpFlags, SNTP_UPDATE_EVENT, TX_OR);
}

/* This application updates Time from SNTP to STM32 RTC */
static void rtc_time_update(NX_SNTP_CLIENT *client_ptr)
{
  RTC_DateTypeDef sdatestructure;
  RTC_TimeTypeDef stimestructure;
  struct tm ts;
  CHAR  temp[2] = {0, 0};
  
  /* convert SNTP time (seconds since 01-01-1900 to 01-01-1970)
  
  EPOCH_TIME_DIFF is equivalent to 70 years in sec
  calculated with www.epochconverter.com/date-difference
  This constant is used to delete difference between :
  Epoch converter (referenced to 1970) and SNTP (referenced to 1900) */
  time_t timestamp = client_ptr->nx_sntp_current_server_time_message.receive_time.seconds - EPOCH_TIME_DIFF;
  
  /* convert time in yy/mm/dd hh:mm:sec */
  ts = *localtime(&timestamp);
  
  /* convert date composants to hex format */
  sprintf(temp, "%ld",  (unsigned long)(ts.tm_year - 100));
  sdatestructure.Year = strtol(temp, NULL, 16);
  sprintf(temp, "%ld", (unsigned long) (ts.tm_mon + 1));
  sdatestructure.Month = strtol(temp, NULL, 16);
  sprintf(temp, "%d", ts.tm_mday);
  sdatestructure.Date = strtol(temp, NULL, 16);
  /* dummy weekday */
  sdatestructure.WeekDay =0x00;
  
  if (HAL_RTC_SetDate(&RtcHandle, &sdatestructure, RTC_FORMAT_BCD) != HAL_OK)
  {
    Error_Handler();
  }
  /* convert time composants to hex format */
  sprintf(temp,"%d", ts.tm_hour);
  stimestructure.Hours = strtol(temp, NULL, 16);
  sprintf(temp,"%d", ts.tm_min);
  stimestructure.Minutes = strtol(temp, NULL, 16);
  sprintf(temp, "%d", ts.tm_sec);
  stimestructure.Seconds = strtol(temp, NULL, 16);
  
  if (HAL_RTC_SetTime(&RtcHandle, &stimestructure, RTC_FORMAT_BCD) != HAL_OK)
  {
    Error_Handler();
  }
  
}

/* this application displays time from RTC */
static void display_rtc_time(RTC_HandleTypeDef *hrtc)
{
  RTC_TimeTypeDef RTC_Time;
  RTC_DateTypeDef RTC_Date;
  
  HAL_RTC_GetTime(&RtcHandle,&RTC_Time,RTC_FORMAT_BCD);
  HAL_RTC_GetDate(&RtcHandle,&RTC_Date,RTC_FORMAT_BCD);
  
  printf("%02x-%02x-20%02x / %02x:%02x:%02x\r\n",\
        RTC_Date.Date, RTC_Date.Month, RTC_Date.Year,RTC_Time.Hours,RTC_Time.Minutes,RTC_Time.Seconds);

}

static UINT unix_time_get(ULONG *unix_time)
{
  RTC_TimeTypeDef RTC_Time;
  RTC_DateTypeDef RTC_Date;
  HAL_RTC_GetTime(&RtcHandle,&RTC_Time,RTC_FORMAT_BIN);
  HAL_RTC_GetDate(&RtcHandle,&RTC_Date,RTC_FORMAT_BIN);

  uint8_t hh = RTC_Time.Hours;
  uint8_t mm = RTC_Time.Minutes;
  uint8_t ss = RTC_Time.Seconds;
  uint8_t d = RTC_Date.Date;
  uint8_t m = RTC_Date.Month;
  uint16_t y = RTC_Date.Year;
  uint16_t yr = (uint16_t)(y+2000-1900);
  time_t currentTime = {0};
  struct tm tim = {0};
  tim.tm_year = yr;
  tim.tm_mon = m - 1;
  tim.tm_mday = d;
  tim.tm_hour = hh;
  tim.tm_min = mm;
  tim.tm_sec = ss;
  currentTime = mktime(&tim);

  /* Return number of seconds since Unix Epoch (1/1/1970 00:00:00).  */
  *unix_time =  (ULONG)currentTime;

  return(NX_SUCCESS);
}
/* USER CODE END 1 */
`

**Comment by dsilva-vd** [comment]
Forgot to attach the console output 

`
Nx_SNTP_Client application started..
STM32 IpAddress: XXX.XXX.X.XXX
SNTP client connected to NTP server : < fr.pool.ntp.org > 

SNTP update :
Mar 24, 2022 15:29:10.374 UTC 

24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
[INFO] Azure IoT Security Module has been enabled, status=0
IoTHub Host Name: myhub.azure-devices.net; Device ID: stm32F429.
24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
24-03-2022 / 15:29:10
24-03-2022 / 15:29:12
24-03-2022 / 15:29:12
24-03-2022 / 15:29:12
24-03-2022 / 15:29:13
24-03-2022 / 15:29:13
24-03-2022 / 15:29:13
24-03-2022 / 15:29:14
24-03-2022 / 15:29:15
24-03-2022 / 15:29:16
24-03-2022 / 15:29:16
24-03-2022 / 15:29:16
24-03-2022 / 15:29:17
24-03-2022 / 15:29:18
24-03-2022 / 15:29:19
24-03-2022 / 15:29:19
24-03-2022 / 15:29:19
24-03-2022 / 15:29:19
24-03-2022 / 15:29:20
24-03-2022 / 15:29:21
[ERROR] IoTHub client connect fail: MQTT CONNECT FAIL status: 65541
Disconnected from IoTHub!: error code = 0x00010005
Failed on nx_azure_iot_hub_client_connect!
reconnecting iothub, after backoff
24-03-2022 / 15:29:22
24-03-2022 / 15:29:22
24-03-2022 / 15:29:22
24-03-2022 / 15:29:23
24-03-2022 / 15:29:24
24-03-2022 / 15:29:25
24-03-2022 / 15:29:25
24-03-2022 / 15:29:25
24-03-2022 / 15:29:25
24-03-2022 / 15:29:25
24-03-2022 / 15:29:26
24-03-2022 / 15:29:28
24-03-2022 / 15:29:28
24-03-2022 / 15:29:28
24-03-2022 / 15:29:28
24-03-2022 / 15:29:29
24-03-2022 / 15:29:30
24-03-2022 / 15:29:31
24-03-2022 / 15:29:31
24-03-2022 / 15:29:31
24-03-2022 / 15:29:32
24-03-2022 / 15:29:33
24-03-2022 / 15:29:33
24-03-2022 / 15:29:34
24-03-2022 / 15:29:34
24-03-2022 / 15:29:34
24-03-2022 / 15:29:35
`

**Comment by TiejunMS** [comment]
Hi @dsilva-vd , I saw there are only 10 packets in the pool. What is the value of RX BD? One simple test you can try is to increase packet pool count from 10 to 30 and see if the problem is solved.

**Comment by dsilva-vd** [comment]
Hi @TiejunMS I increased NX_APP_MEM_POOL_SIZE to 70kBytes and increased the packet pool count to 30. This didn't change the behavior.

Just to confirm these are the changes I made:
`
#define PAYLOAD_SIZE                 1536
#define NX_PACKET_POOL_NUM_PACKETS   30
#define NX_PACKET_POOL_SIZE          (( PAYLOAD_SIZE + sizeof(NX_PACKET)) * NX_PACKET_POOL_NUM_PACKETS)
`

PACKET_POOL_SIZE is used to allocate the packet pool

What is RX BD? Can you point me to a file or name of define I can search for?
Thanks

**Comment by TiejunMS** [comment]
If you are using official driver from ST, then the value is defined [here](https://github.com/STMicroelectronics/x-cube-azrtos-f4/blob/5a854b28de9e67380f65c7e2b852e3add0fb9000/Middlewares/ST/netxduo/common/drivers/ethernet/nx_stm32_eth_driver.h#L97). Since the problem is not solved after increasing the packet pool, it is not due to lack of packet. Are you able to capture packet trace by wireshark and share with us? It is helpful to understand what happens during the connection.

**Comment by dsilva-vd** [comment]
Hi I will try and capture a Wireshark but as the device is a wired device I will try and find a way to do man in the middle listening.

The defines are as follows

`
#define ETH_MAX_PACKET_SIZE       1524U    /*!< ETH_HEADER + ETH_EXTRA + ETH_VLAN_TAG + ETH_MAX_ETH_PAYLOAD + ETH_CRC */
#define ETH_RX_BUF_SIZE                ETH_MAX_PACKET_SIZE /* buffer size for receive               */
#define ETH_TX_BUF_SIZE                ETH_MAX_PACKET_SIZE /* buffer size for transmit              */
#define ETH_RXBUFNB                    4U       /* 4 Rx buffers of size ETH_RX_BUF_SIZE  */
#define ETH_TXBUFNB                    4U       /* 4 Tx buffers of size ETH_TX_BUF_SIZE  */
`

**Comment by dsilva-vd** [comment]
[ST32 Ethernet - bridge mode adapter.zip](https://github.com/azure-rtos/netxduo/files/8366850/ST32.Ethernet.-.bridge.mode.adapter.zip)
Hi @TiejunMS Here is a wireshark capture. The ST32 device has address 192.168.0.126. The network connectivity is bridged through 192.168.0.143 (which was running Wireshark).  

I don't see any packets from the the ST32 device indicating it is starting the MQTT connection to the Azure IoT Hub. I await your thoughts on reviewing the wireshark capture.
Thanks

**Comment by TiejunMS** [comment]
@dsilva-vd , it does not look like the bridge is working. Could you double check the bridge configurations?

Btw, if you would like to share your sample_config.h with us for checking, feel free to send it to azure-rtos-support@microsoft.com

**Comment by dsilva-vd** [comment]
@TiejunMS Here are the files for my iot client. I believe I renamed the sample_config.h to azure_iot_client_config.h  
[IoTClient.zip](https://github.com/azure-rtos/netxduo/files/8367762/IoTClient.zip)

I will look into the bridging configuration again tomorrow. Thanks

**Comment by TiejunMS** [comment]
@dsilva-vd , could you fill in the valid hostname, device_id and symmetric key in the config.h? Just want to double check the configurations are all correct. You can delete the device once it is verified. To avoid credential leak publicly, you can send it through support email listed above.

**Comment by dsilva-vd** [comment]
@TiejunMS I sent in the config file with credentials to the support email today. I'll keep working on the wireshark capture.

**Comment by TiejunMS** [comment]
@dsilva-vd , I have verified the credentials you shared are valid in our official sample. If you are using the same sample, then the issue might be related to Ethernet driver. Did you port the driver or it is provided by ST? Anyway, a packet trace will be helpful to show us what happened during the connection.

**Comment by dsilva-vd** [comment]
@TiejunMS The Ethernet driver is provided by ST in an example on setting up a simple SNTP client (using Ethernet). I took that example and after successfully connecting to SNTP server and getting a time update I start the Azure IoT embedded client thread.

**Comment by dsilva-vd** [comment]
@TiejunMS I'm closing this issue. STM has released an AZure RTOS version of their cellular FW package and my end goal is azure connection with cellular PPP interface. The ethernet example was for temporary development. I will re-integrate the azure iot embedded client with the cellular FW package and open a new ticket if I encounter any issues.

Thanks

**Comment by TiejunMS** [comment]
Thanks for letting me know. Feel free to reopen the issue if needed.

**Comment by dsilva-vd** [comment]
@TiejunMS I need to reopen this issue.  

I have been able to integrate the Azure IoT client  (sample_azure_iot_embedded_skd_with_retry, Netxduo 6.1.7 release) with the Azure RTOS STM32 Cellular package.  

The IoT client behavior is exactly the same as when I was running the client over Ethernet.  The same function call returns the error value. The last time you helped troubleshoot this issue you wanted to see a Wireshark capture. That won't be simple with the cellular modem so is there another option to troubleshoot this? 

I could purchase the same reference kit used in the Netx example code i.e. B-L475E-IOT01A2 (B-L475E-IOT01A1) and run the same example to capture Wireshark but as that example works I'm not sure what it would tell us.  

if this is helpful I've attached a screenshot of the ThreadX thread list the moment the mqtt connect call is made. Perhaps there is a thread priority issue that you can see
![image](https://user-images.githubusercontent.com/60989663/166980278-939c9471-2205-4645-b5c0-33caf7728454.png)

**Comment by dsilva-vd** [comment]
Forgot to reopen issue

**Comment by TiejunMS** [comment]
@dsilva-vd , since you were able to reproduce the issue on both Ethernet and Cellular interfaces, I think the issue is related to application. So could you capture the packets through Ethernet which should be much simpler?

**Comment by dsilva-vd** [comment]
Hi @TiejunMS I captured a wireshark capture using an passive network tap. I'm not sure I have the correct wireshark settings but here is the captured log. The device's IP is 192.168.0.138
[Ethernet Azure IoT Hub capture.zip](https://github.com/azure-rtos/netxduo/files/8655486/Ethernet.Azure.IoT.Hub.capture.zip)

**Comment by dsilva-vd** [comment]
Updated capture. The first one was not captured properly and I deleted it.  I can see from the logs there is a TLS failure (Fatal Alert)
[Ethernet Azure IoT Hub capture.zip](https://github.com/azure-rtos/netxduo/files/8655773/Ethernet.Azure.IoT.Hub.capture.zip)

**Comment by dsilva-vd** [comment]
Hi @TiejunMS ,

I had removed the 1st cert as I saw the comment that MS was going to transition to Digicert and removed it. After adding the cert back in the Ethernet example worked.  I also found on the ethernet sample that I needed a larger packet pool for Net X.  

I made the same changes (adding back in root cert 1) on my cellular example and successfully connected there as well.  

Thank you for your help!

**Comment by TiejunMS** [comment]
Good to know it is working!

**Comment by bo-ms** [comment]
Hi @dsilva-vd, the start date of the Azure IoT root certificate migration from June1st 2022, to no earlier than Feb 15th, 2023. you may check here: https://techcommunity.microsoft.com/t5/internet-of-things-blog/azure-iot-tls-critical-changes-are-almost-here-and-why-you/ba-p/2393169
