### ISSUE TITLE
Is there a define to know if Netxduo has been added to the build?

### ISSUE THREAD

**Issue by josesimoes** [azure-rtos/netxduo#87]
Hi,

This may sound a bit dumb of a question, but I can't find a satisfactory answer by looking at the code...
In ThreadX, there is this define `AZURE_RTOS_THREADX` that can be used to know if ThreadX has been brought into the build. I can't find an equivalent define for NetX. Is there one?

**Comment by TiejunMS** [comment]
The equivalent define of NetX Duo is [AZURE_RTOS_NETXDUO](https://github.com/azure-rtos/netxduo/blob/fbac46913473930d65c389fef3580a6bd1f15817/common/inc/nx_api.h#L496).

**Comment by josesimoes** [comment]
Confirmed: it was a dumb question... 😯 🤦🏻‍♂️ 😅 
I've must have mistype it in my searches and completely missed it.
@TiejunMS thanks!
