### ISSUE TITLE
NX_SECURE_TLS_PREMASTER_SIZE too small for PSK 63 bytes key

### ISSUE THREAD

**Issue by DoudFPV** [azure-rtos/netxduo#88]
With PSK, the nx_secure_tls_pre_master_secret is too small for 63 bytes PSK key.  

Default NX_SECURE_TLS_PREMASTER_SIZE is 68 or 48bytes but should be :  
```
#define NX_SECURE_TLS_PREMASTER_SIZE                      (2 + 2 + NX_SECURE_TLS_MAX_PSK_SIZE + NX_SECURE_TLS_MAX_PSK_SIZE + 1) 
```

    /* From RFC 4279:
    The premaster secret is formed as follows: if the PSK is N octets
    long, concatenate a uint16 with the value N, N zero octets, a second
    uint16 with the value N, and the PSK itself.
    |   2   |   <N>  |   2   |   <N>   |
    |   N   |    0   |   N   |   PSK   |

**Comment by yanwucai** [comment]
I think you can define NX_SECURE_TLS_PREMASTER_SIZE to a larger size in nx_secure_user.h if you need long PSK keys.

**Comment by DoudFPV** [comment]
Yes I did.

But today with default value, NX_SECURE_TLS_MAX_PSK_SIZE is 64, and handshake failed if the key si bigger than 33 bytes, that is why it looks like an issue for me.

**Comment by yanwucai** [comment]
We have updated the default value of NX_SECURE_TLS_PREMASTER_SIZE when PSK is enabled, and the fix will be released in the next release.

**Comment by DoudFPV** [comment]
Thanks I appreciate
