### ISSUE TITLE
使用DHCP请求设置静态IP返回NCK

### ISSUE THREAD

**Issue by chengshuihang** [azure-rtos/netxduo#95]
我使用静态IP通过USB ECM访问EC20设备，跳过DHCP Discover，使用DHCP Request设置IP，发现返回NCK，错误信息为"wrong server-ID"。原因是DHCP发送了服务器IP为NX_BOOTP_NO_ADDRESS，我通过修改条件，过滤掉它，DHCP设置成功，EC20返回了ACK。代码如下：
![9832966253dce67ecd525a67cc50e7f](https://user-images.githubusercontent.com/45716763/164890792-6f7d8f59-4a13-4b4d-aaa3-d66b6d81e2dd.png)

**Comment by bo-ms** [comment]
@chengshuihang  谢谢，是的，这是一个bug，我们会在下一个版本中修复这个问题，你可以先本地这样修改。

**Comment by bo-ms** [comment]
Closing
