### ISSUE TITLE
nxd_ipv6_stateless_address_autoconfig_enable api usage

### ISSUE THREAD

**Issue by RishaHolla** [azure-rtos/netxduo#99]
I am testing IPV6 IP address assignment using SLAAC for netx stack. I need to understand under what condition should nxd_ipv6_stateless_address_autoconfig_enable() api should be called to enable SLAAC?
1. When the ip address is tried to be configured for a interface via DHCPv6 server and it fails, enable SLAAC?
2. When we get a RA from server with O,A flags set asking to start SLAAC, enable the feature right before starting SLAAC?
3. Enable the feature via host input via host commands for the whole stack irrespective of the interface or for a specific interface?
4. Or in any other context?

Do you have a demo application indicating its usage?.

**Comment by TiejunMS** [comment]
@RishaHolla, NetXDuo will start SLAAC once the **link local IPv6 address is set** and ICMPv6 is enabled. The API `nxd_ipv6_stateless_address_autoconfig_enable()` is needed only when SLAAC is disabled manually in user application by `nxd_ipv6_stateless_address_autoconfig_disabble()` and you want to enable it again.

The choice of using SLAAC or DHCPv6 depends on your local network setup.

**Comment by TiejunMS** [comment]
Closing.
